### ISSUE TITLE
Change default panel-toolbar button

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#1]
@rickysut 
views/layouts/admin.blade.php
line 172 - 176:
_<script type="text/javascript">
    $('#js-page-content').smartPanel();
</script>_

fungsi ini di **disable** (mark as comment), ** karena client ingin button warna diubah menjadi icon**.

contoh pada panel-toolbar di vip.blade.php:
![image](https://user-images.githubusercontent.com/108628095/181400936-49f02a8a-d4bf-47ae-ba14-1ad752dc7d70.png)

_di lokal saya sudah saya ubah, memohon ijin dari administrator untuk mengunggah perubahan ke repo._

**Comment by rickysut** [comment]
<img width="562" alt="Screen Shot 2022-07-28 at 09 43 05" src="https://user-images.githubusercontent.com/27186274/181408862-0ac25098-6c31-49f0-9d9c-b1f72abe234b.png">

beda

**Comment by rickysut** [comment]
push aja design terbarunya pak

**Comment by rickysut** [comment]
{{-- <script type="text/javascript">
            /* Activate smart panels */
            $('#js-page-content').smartPanel();
			
        </script> --}}

sudah diremark dan diganti icon detail nya
