### ISSUE TITLE
admin/pagu: Tab/Pills Kinerja Kegiatan Widget 1

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#10]
@rickysut @rickysutanto 

**Penjelasan Widget**
![image](https://user-images.githubusercontent.com/108628095/184173465-2a6fe744-ef1f-4c1d-a551-58c8dbd418b8.png)

1. Donut/Pie
adalah % total Realisasi (data_realisasis) dibagi Pagu (data_pagus)

2. Nilai Rupiah
a. adalah nilai total Realisasi (data_realisasis)
b. tambahkan dibawahnya nilai total Pagu (data_pagus)

3. Bar Chart
a. terbagi ke dalam 6 segmen (berdasar kode kegiatan)
b. tiap segmen terbagi ke dalam 4 time range.
c. bar on hover adalah prosentase nilai realisasi terhadap pagu (per kegiatan)

4. Segmen
a. tidak menggunakan nama direktorat (STO, Buflo, dll) namun gunakan kode (1771, 1773, dst),
b. tambahkan Legend kode kegiatan dengan nomenklatur kegiatan di bagian bawah/luar chart.

5. Time Range
a. TW1 = Q1, start 01 Jan s.d 31 Mar (akumulasi)
b. TW2 = Q2, start 01 Jan s.d 30 Jun (akumulasi)
c. TW3 = Q3, start 01 Jul s.d 30 Sept (akumulasi)
d. TW4 = Q4, 1 tahun penuh (akumulasi)

**IMPORTANT
sepertinya bagian ini tidak cocok jika menggunakan filter multiyears**

**Comment by rickysut** [comment]
a. terbagi ke dalam 6 segmen (berdasar kode kegiatan) **ada 7 di master kegiatan**, bagaimana jika ada penambahan di master kegiatannya?

**Comment by rickysut** [comment]
sepertinya bagian ini tidak cocok jika menggunakan filter multiyears.. **benar, TW1 multiyear datanya jadi tidak tepat, yg namanya triwulan hanya per tahun**

**Comment by rickysut** [comment]
<img width="543" alt="Screen Shot 2022-08-13 at 00 17 36" src="https://user-images.githubusercontent.com/27186274/184410450-965e2d61-8282-4bf9-b7de-009b3c1df6c7.png">
untuk legend nya coba carikan cara sort nya pak TW1 - TW4 biar urut
