### ISSUE TITLE
admin/pagu: Tab/Pills Kinerja Kegiatan Widget 2

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#11]
@rickysut @rickysutanto 

Penjelasan Widget 2
![image](https://user-images.githubusercontent.com/108628095/184178764-ce736832-b39b-4185-841c-b41871970820.png)

No.1
Nama Kegiatan (dari kode kegiatan)

No. 2
Nilai Realisasi (data_realisasis)

No. 3
prosentase dari total Realisasi per Kegiatan (data_realisasis by kd_giat) vs Pagu per kegiatan (data_pagus by kd_giat)

**Comment by rickysut** [comment]
done
