### ISSUE TITLE
Executive Summary Dashboard RENJA

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#12]
@rickysut @rickysutanto 

Dashboard RENJA
![image](https://user-images.githubusercontent.com/108628095/184182936-22bbc425-c72c-4c4b-8337-a786d23d4bc1.png)

No. 1 Donut/Pie,
nilai % diperoleh dari:
sum field "jumlah" by "kdgiat" dibagi sum "jumlah" pada table data_renjas

No. 2 Nomenklatur
table data_renjas field "kdgiat" relasi ke table master_kegiatans field nomenklatur_giat, jangan gunakan field "direktorat".

No. 3
nilai Rupiah diperoleh dari:
sum field "jumlah" by "kdgiat" pada table data_renjas

**Comment by rickysut** [comment]
@sultanjawer  done
