### ISSUE TITLE
Koreksi kolom satuan pada tabel 

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#13]
halaman contoh: admin/detrenjaview/0601/KAB.%20ACEH%20BESAR

![image](https://user-images.githubusercontent.com/108628095/184184119-785db08a-a8b9-42a0-8633-cabd0f788aec.png)

![image](https://user-images.githubusercontent.com/108628095/184185242-87485ad7-3708-46ca-abb6-0d3570606d50.png)

![image](https://user-images.githubusercontent.com/108628095/184185073-94aba052-2cf1-452b-8fea-79542abd367e.png)

di db lokal saya (dan juga permintaan klien), tidak ada satuan HA, unit, dsb. berdasarkan pada table data_renjas serta contoh file [**excel xls**](https://github.com/rickysut/simevi_retheme/files/9310311/BACKUP_DETIL_RENJA_REGULER_2022.xls) yang dikirim. untuk itu, satuan tidak perlu di relasikan ke tabel/field lain. langsung menggunakan field satuan dengan isi "kegiatan".

**Comment by rickysut** [comment]
satuan pakai table rincian_output pak

**Comment by rickysut** [comment]
dihilangkan
