### ISSUE TITLE
Tahun Dinamis Table Data Renjas

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#14]
![image](https://user-images.githubusercontent.com/108628095/184189507-c172bb51-cbe5-4b4d-a9e3-fdfe4fd50d00.png)

apakah kolom tahun ini sudah dimanis, sehingga jika berganti tahun (data tahun yang baru diunggah), maka kolom terakhir menjadi tahun terakhir?

bagaimana menerapkan filter multiyears untuk kasus di sini? ada saran?

**Comment by rickysut** [comment]
apakah kolom tahun ini sudah dimanis, sehingga jika berganti tahun (data tahun yang baru diunggah), maka kolom terakhir menjadi tahun terakhir? **Belum**

**Comment by rickysut** [comment]
bagaimana menerapkan filter multiyears untuk kasus di sini? ada saran? **Bisa kok**, nanti kalau pilihannya kurang dari 4 kolom disesuaikan..tapi kalau lebih dari 4 di warning saja supaya maks pilihan 4 tahun

**Comment by rickysut** [comment]
ok sudah skrg @sultanjawer
