### ISSUE TITLE
Perubahan layout detail peta.

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#2]
@rickysut 
client menginginkan:
1. ditambahkan symbol **%** setelah angka prosen pada pie (center).
![image](https://user-images.githubusercontent.com/108628095/181396161-96ab44cc-7f5a-4e6e-a0ca-dea611521acb.png)
(done di lokal saya)

2. penambahan informasi nilai rupiah (rupiah barang-rupiah uang)
  a. baris judul kewenangan ditarik ke atas pie rata kiri
![image](https://user-images.githubusercontent.com/108628095/181397703-f0dc099c-be67-42c0-942f-a643e1367291.png)

baris nilai rupiah menjadi 2 baris:
a. rupiah barang
b. rupiah uang
![image](https://user-images.githubusercontent.com/108628095/181397816-493768dd-1ce3-4b38-b3ed-123b293b2bc6.png)

**Comment by rickysut** [comment]
1. ditambahkan symbol % setelah angka prosen pada pie (center). (tdk bisa dilakukan -- keterbatasan komponen)
2. total berarti tidak ada ya? di pecah uang sendiri, barang sendiri

**Comment by rickysut** [comment]
done
