### ISSUE TITLE
Provinsi pada peta

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#3]
@rickysut 

case:
saat klik peta provinsi papua, pada datatable muncul 2 provinsi: 1. Prov. Papua dan; 2. Prov. Papua Barat.

expected:
saat klik peta provinsi, hanya menampilkan provinsi yang dipilih saja.

![image](https://user-images.githubusercontent.com/108628095/181398798-c5e0ec56-25d6-4db4-a1f6-6eccd6fcde6d.png)

**Comment by rickysut** [comment]
tidak bisa, karena mengandalkan teks untuk filter

**Comment by rickysut** [comment]
data yg ditampilkan pada peta , bisa jadi juga gabungan papua dan papua barat
