### ISSUE TITLE
Filter Tahun

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#4]
@rickysut 
saran/keinginan klien, namun belum saya setujui

semula:
**Single Year**
![image](https://user-images.githubusercontent.com/108628095/181398905-23ffe370-a1d9-42af-aca1-37677aa70363.png)

_**data yang ditampilkan adalah akumulasi pada tahun tunggal yang dipilih**_

menjadi:
**Year to Year**
![image](https://user-images.githubusercontent.com/108628095/181400146-35d8d25f-46ec-47ae-87d2-15b21468191c.png)

_**data yang ditampilkan adalah akumulasi range tahun (multi years) yang dipilih (hingga ke datatable)**_

**Comment by rickysut** [comment]
done
