### ISSUE TITLE
Kinerja Anggaran Detail

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#5]
@rickysut 

akses dari vipdashboard
![image](https://user-images.githubusercontent.com/108628095/181401396-e2158980-6db6-482f-a232-544df26d5d72.png)

lalu klik detail pada panel toolbar, muncul halaman:
![image](https://user-images.githubusercontent.com/108628095/181401551-8e1f4418-32f1-4497-a76b-1fb0703aa2c0.png)
klien pun ingin filter tahun ini menjadi **Year to Year**.

juga untuk dashboard-dashboard lainnya (baru saya tampung pendapat, belum saya katakan kesanggupan ke klien)

**Comment by rickysut** [comment]
<img width="1114" alt="Screen Shot 2022-07-28 at 17 18 08" src="https://user-images.githubusercontent.com/27186274/181482510-b773336a-cf00-4a95-8231-f9ae6bf07486.png">
ini designya di fix dulu pak.. 

untuk uang dan barang apa sama dengan yang detail banpem tuh..  (issue 3)

**Comment by rickysut** [comment]
lihat Perubahan layout detail peta. #2

**Comment by sultanjawer** [comment]
untuk barang dan uang, sama seperti banpem om, parameter dari kode akun.
dibuat/disiapkan saja nilai barang dan uang, suatu saat perlu, tinggal dikeluarkan.

untuk tampilan beranda ini adalah PAGU-REALISASI
