### ISSUE TITLE
Nilai Kinerja Percepatan

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#7]
saya coba bandingkan versi update 31/07 ini.
(tapi mohon periksa yang ditampilkan pada web versi om riki, apakah sama dengan lokal saya)

saya tidak tahu, darimana NKP pada powerpoint yang ada sehingga nilainya berbeda dengan NKP versi web..

**ss dari Satker DKI Jakarta + Jawa Barat 2021:**
![image](https://user-images.githubusercontent.com/108628095/182033181-e357142a-952f-410f-a774-af0d4be9e179.png)

**ss powerpoint DKI Jakarta + Jawa Barat 2021:**
![image](https://user-images.githubusercontent.com/108628095/182033165-43ecc3a9-6b89-478c-9a0f-72d71a117795.png)

**Overview**
Target serapan pada:

1. TW1 = 15%,

    Condition
    Q1 = total realisasi 1 Jan - 31 Mar

   Formula:
   X% = ∑realisasi Q1/Pagu
   TW1 = (X% / 15%)*100
   jika >15% = 100
  

2. TW2 = 40%,

    Condition
    Q2 = total realisasi  1 Jan - 30 Jun

   Formula:
   X% = ∑realisasi Q2/Pagu
   TW2 = (X% / 40%)*100
    If TW2 > 40% = 100

3. TW3 = 60%

    Condition
    Q3 = total realisasi  1 Jan - 31 Sep

   Formula:
   X% = ∑realisasi Q3/Pagu
   TW3 = (X% / 60%)*100
    If TW3 > 60% = 100

4. TW4 = 100%,

    Condition
    Q4 = total realisasi 1 Jan - 31 Des

   Formula:
   TW4 = ∑realisasi Q4/Pagu

**Comment by rickysut** [comment]
<img width="1116" alt="Screen Shot 2022-08-12 at 19 58 52" src="https://user-images.githubusercontent.com/27186274/184358866-6480ce72-b6e6-4b92-8abb-506ff405d8c2.png">
sepertinya sudah ok
