### ISSUE TITLE
admin/pagu: Tab Kinerja Program

### ISSUE THREAD

**Issue by sultanjawer** [rickysut/simevi_retheme#8]
@rickysut @rickysutanto 
![image](https://user-images.githubusercontent.com/108628095/184164566-fbaebb1e-6d5c-4d1b-b083-3cc2feb2bc35.png)

Keterangan
No. 1 Kode Program
	a. Gunakan tbl_program.csv sebagai referensi
	b. Lihat table data_pagus/data_realisasis. field "program". kode program melekat pada "01804HA". saya menggunakan _Right([program],2)_ untuk mendapatkan kode program. kemudian saya relasikan ke [tbl_program.csv](https://github.com/rickysut/simevi_retheme/files/9309702/tbl_program.csv)

No. 2 Nomenklatur Kode Program
	a. menggunakan [tbl_program.csv](https://github.com/rickysut/simevi_retheme/files/9309702/tbl_program.csv) sebagai relasi kode
	
No. 3 Donut/Pie
	a. adalah nilai Prosentase Total Realisasi (data_realisasis) per kode program terhadap Total Pagu per kode program (data_pagus)

No. 4 Nilai Total Realisasi (data_realisasis) untuk kode program terkait

No. 5 Nilai Total Pagu (data_pagus) untuk kode program terkait

**IMPORTANT NOTE:
terdapat perbedaan kode program antara tahun 2019-2020 (menggunakan numeric, belum ada keterangan arti numeric)  dengan 2021-2022 (menggunakan alfabet, keterangan arti sesuai dengan [tbl_program.csv](https://github.com/rickysut/simevi_retheme/files/9309702/tbl_program.csv)).**

**Comment by rickysut** [comment]
done
